### ISSUE TITLE
Possibility to exclude tests

### ISSUE THREAD

**Issue by janedbal** [pepakriz/phpstan-exception-rules#24]
Currently I need to catch or annotate all checked exceptions in my tests, but it is quite useless work (exception thrown in test will just cause the test to fail). Is there any way to exclude test files (by namespace or classname or parent class or whatever) from this check? It would be really useful I think.

**Comment by Stadly** [comment]
I solve this by using two different phpstan configuration files. One for my source files, where the exception rules are included:
```
# phpstan.neon.dist
parameters:
    level: max
    paths:
        - src
    exceptionRules:
        reportUnusedCatchesOfUncheckedExceptions: true
        uncheckedExceptions:
            - LogicException

includes:
    - vendor/pepakriz/phpstan-exception-rules/extension.neon
```

And one for my test files, where the exception rules are not included (but some phpunit test are).
```
# phpstan.tests.neon.dist
parameters:
    level: max
    paths:
        - tests

includes:
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
```

Then phpstan must be run twice:
```
phpstan analyse
phpstan analyse -c phpstan.tests.neon.dist
```

But a way to exclude exception testing from all test files would definitely be an easier solution!
