### ISSUE TITLE
Let method throw exception using methodThrowTypeDeclarations

### ISSUE THREAD

**Issue by Stadly** [pepakriz/phpstan-exception-rules#25]
How can I use `methodThrowTypeDeclarations` to override a parent method definition and let child method implementations throw exceptions?

Consider the following code:

```php
abstract class Foo
{
    abstract public function test(): void;
}
```

```php
class Bar extends Foo
{
    /**
     * @throws \RuntimeException
     */
    public function test(): void
    {
        throw new \RuntimeException();
    }
}
```
Using a configuration like this:

```yaml
parameters:
    exceptionRules:
        checkedExceptions:
            - RuntimeException
        methodThrowTypeDeclarations:
            Foo:
                test:
                    - RuntimeException

includes:
    - vendor/pepakriz/phpstan-exception-rules/extension.neon
```

I get the following error report:

```
 ------ -----------------------------------------------------------------------------
  Line   src\Bar.php
 ------ -----------------------------------------------------------------------------
  10     PHPDoc tag @throws with type RuntimeException is not compatible with parent
 ------ -----------------------------------------------------------------------------
```

The use case here is that `Foo` is part of some library that does not use `@throws` annotations.
