### ISSUE TITLE
Invalid configuration: parameters › exceptionRules

### ISSUE THREAD

**Issue by solcik** [pepakriz/phpstan-exception-rules#85]
# Bug report

```
"name": "phpstan/phpstan",
"version": "0.11.7",
"name": "pepakriz/phpstan-exception-rules",
"version": "v0.8.1",
```

Error: ```Invalid configuration: parameters › exceptionRules```
Introduces by https://github.com/phpstan/phpstan/commit/54a125df47fa097b792cb9a3e70c49f753f66b85

### Code snippet that reproduces the problem

Config:
```
includes:
    - vendor/pepakriz/phpstan-exception-rules/extension.neon
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon

parameters:
    exceptionRules:
        uncheckedExceptions:
            - Nette\Application\AbortException
```

I have to disable `validateParameters` from `bleedingEdge` to overcome the problem.

```
parameters:
    featureToggles:
        validateParameters: false
```
